import { TUser } from 'types/main';

export const DEFAULT_LIST_USERS: TUser[] = [
  {
    login: 'bezsmertnyi',
    id: 23166432,
    node_id: 'MDQ6VXNlcjIzMTY2NDMy',
    avatar_url: 'https://avatars.githubusercontent.com/u/23166432?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/bezsmertnyi',
    html_url: 'https://github.com/bezsmertnyi',
    followers_url: 'https://api.github.com/users/bezsmertnyi/followers',
    following_url:
      'https://api.github.com/users/bezsmertnyi/following{/other_user}',
    gists_url: 'https://api.github.com/users/bezsmertnyi/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/bezsmertnyi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/bezsmertnyi/subscriptions',
    organizations_url: 'https://api.github.com/users/bezsmertnyi/orgs',
    repos_url: 'https://api.github.com/users/bezsmertnyi/repos',
    events_url: 'https://api.github.com/users/bezsmertnyi/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/bezsmertnyi/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
  {
    login: 'igorbezsmertnyi',
    id: 21984930,
    node_id: 'MDQ6VXNlcjIxOTg0OTMw',
    avatar_url: 'https://avatars.githubusercontent.com/u/21984930?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/igorbezsmertnyi',
    html_url: 'https://github.com/igorbezsmertnyi',
    followers_url: 'https://api.github.com/users/igorbezsmertnyi/followers',
    following_url:
      'https://api.github.com/users/igorbezsmertnyi/following{/other_user}',
    gists_url: 'https://api.github.com/users/igorbezsmertnyi/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/igorbezsmertnyi/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/igorbezsmertnyi/subscriptions',
    organizations_url: 'https://api.github.com/users/igorbezsmertnyi/orgs',
    repos_url: 'https://api.github.com/users/igorbezsmertnyi/repos',
    events_url: 'https://api.github.com/users/igorbezsmertnyi/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/igorbezsmertnyi/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
  {
    login: 'mrdeathless',
    id: 286884,
    node_id: 'MDQ6VXNlcjI4Njg4NA==',
    avatar_url: 'https://avatars.githubusercontent.com/u/286884?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mrdeathless',
    html_url: 'https://github.com/mrdeathless',
    followers_url: 'https://api.github.com/users/mrdeathless/followers',
    following_url:
      'https://api.github.com/users/mrdeathless/following{/other_user}',
    gists_url: 'https://api.github.com/users/mrdeathless/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/mrdeathless/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mrdeathless/subscriptions',
    organizations_url: 'https://api.github.com/users/mrdeathless/orgs',
    repos_url: 'https://api.github.com/users/mrdeathless/repos',
    events_url: 'https://api.github.com/users/mrdeathless/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mrdeathless/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
  {
    login: 'AllroadDev',
    id: 33293268,
    node_id: 'MDQ6VXNlcjMzMjkzMjY4',
    avatar_url: 'https://avatars.githubusercontent.com/u/33293268?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/AllroadDev',
    html_url: 'https://github.com/AllroadDev',
    followers_url: 'https://api.github.com/users/AllroadDev/followers',
    following_url:
      'https://api.github.com/users/AllroadDev/following{/other_user}',
    gists_url: 'https://api.github.com/users/AllroadDev/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/AllroadDev/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/AllroadDev/subscriptions',
    organizations_url: 'https://api.github.com/users/AllroadDev/orgs',
    repos_url: 'https://api.github.com/users/AllroadDev/repos',
    events_url: 'https://api.github.com/users/AllroadDev/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/AllroadDev/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
  {
    login: 'VadymBezsmertnyi',
    id: 73135527,
    node_id: 'MDQ6VXNlcjczMTM1NTI3',
    avatar_url: 'https://avatars.githubusercontent.com/u/73135527?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/VadymBezsmertnyi',
    html_url: 'https://github.com/VadymBezsmertnyi',
    followers_url: 'https://api.github.com/users/VadymBezsmertnyi/followers',
    following_url:
      'https://api.github.com/users/VadymBezsmertnyi/following{/other_user}',
    gists_url: 'https://api.github.com/users/VadymBezsmertnyi/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/VadymBezsmertnyi/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/VadymBezsmertnyi/subscriptions',
    organizations_url: 'https://api.github.com/users/VadymBezsmertnyi/orgs',
    repos_url: 'https://api.github.com/users/VadymBezsmertnyi/repos',
    events_url:
      'https://api.github.com/users/VadymBezsmertnyi/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/VadymBezsmertnyi/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
  {
    login: 'besmertn',
    id: 17814785,
    node_id: 'MDQ6VXNlcjE3ODE0Nzg1',
    avatar_url: 'https://avatars.githubusercontent.com/u/17814785?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/besmertn',
    html_url: 'https://github.com/besmertn',
    followers_url: 'https://api.github.com/users/besmertn/followers',
    following_url:
      'https://api.github.com/users/besmertn/following{/other_user}',
    gists_url: 'https://api.github.com/users/besmertn/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/besmertn/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/besmertn/subscriptions',
    organizations_url: 'https://api.github.com/users/besmertn/orgs',
    repos_url: 'https://api.github.com/users/besmertn/repos',
    events_url: 'https://api.github.com/users/besmertn/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/besmertn/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
  {
    login: 'bezsmertnyi-oleksandr',
    id: 114508447,
    node_id: 'U_kgDOBtNCnw',
    avatar_url: 'https://avatars.githubusercontent.com/u/114508447?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/bezsmertnyi-oleksandr',
    html_url: 'https://github.com/bezsmertnyi-oleksandr',
    followers_url:
      'https://api.github.com/users/bezsmertnyi-oleksandr/followers',
    following_url:
      'https://api.github.com/users/bezsmertnyi-oleksandr/following{/other_user}',
    gists_url:
      'https://api.github.com/users/bezsmertnyi-oleksandr/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/bezsmertnyi-oleksandr/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/bezsmertnyi-oleksandr/subscriptions',
    organizations_url:
      'https://api.github.com/users/bezsmertnyi-oleksandr/orgs',
    repos_url: 'https://api.github.com/users/bezsmertnyi-oleksandr/repos',
    events_url:
      'https://api.github.com/users/bezsmertnyi-oleksandr/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/bezsmertnyi-oleksandr/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
  {
    login: 'BezsmertnyiIgor',
    id: 54040617,
    node_id: 'MDQ6VXNlcjU0MDQwNjE3',
    avatar_url: 'https://avatars.githubusercontent.com/u/54040617?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/BezsmertnyiIgor',
    html_url: 'https://github.com/BezsmertnyiIgor',
    followers_url: 'https://api.github.com/users/BezsmertnyiIgor/followers',
    following_url:
      'https://api.github.com/users/BezsmertnyiIgor/following{/other_user}',
    gists_url: 'https://api.github.com/users/BezsmertnyiIgor/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/BezsmertnyiIgor/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/BezsmertnyiIgor/subscriptions',
    organizations_url: 'https://api.github.com/users/BezsmertnyiIgor/orgs',
    repos_url: 'https://api.github.com/users/BezsmertnyiIgor/repos',
    events_url: 'https://api.github.com/users/BezsmertnyiIgor/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/BezsmertnyiIgor/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
  {
    login: 'reify-qa',
    id: 84033436,
    node_id: 'MDQ6VXNlcjg0MDMzNDM2',
    avatar_url: 'https://avatars.githubusercontent.com/u/84033436?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/reify-qa',
    html_url: 'https://github.com/reify-qa',
    followers_url: 'https://api.github.com/users/reify-qa/followers',
    following_url:
      'https://api.github.com/users/reify-qa/following{/other_user}',
    gists_url: 'https://api.github.com/users/reify-qa/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/reify-qa/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/reify-qa/subscriptions',
    organizations_url: 'https://api.github.com/users/reify-qa/orgs',
    repos_url: 'https://api.github.com/users/reify-qa/repos',
    events_url: 'https://api.github.com/users/reify-qa/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/reify-qa/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
  {
    login: 'denisbezsmertnyi',
    id: 60133580,
    node_id: 'MDQ6VXNlcjYwMTMzNTgw',
    avatar_url: 'https://avatars.githubusercontent.com/u/60133580?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/denisbezsmertnyi',
    html_url: 'https://github.com/denisbezsmertnyi',
    followers_url: 'https://api.github.com/users/denisbezsmertnyi/followers',
    following_url:
      'https://api.github.com/users/denisbezsmertnyi/following{/other_user}',
    gists_url: 'https://api.github.com/users/denisbezsmertnyi/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/denisbezsmertnyi/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/denisbezsmertnyi/subscriptions',
    organizations_url: 'https://api.github.com/users/denisbezsmertnyi/orgs',
    repos_url: 'https://api.github.com/users/denisbezsmertnyi/repos',
    events_url:
      'https://api.github.com/users/denisbezsmertnyi/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/denisbezsmertnyi/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
  {
    login: 'obezsmertnyi',
    id: 25085507,
    node_id: 'MDQ6VXNlcjI1MDg1NTA3',
    avatar_url: 'https://avatars.githubusercontent.com/u/25085507?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/obezsmertnyi',
    html_url: 'https://github.com/obezsmertnyi',
    followers_url: 'https://api.github.com/users/obezsmertnyi/followers',
    following_url:
      'https://api.github.com/users/obezsmertnyi/following{/other_user}',
    gists_url: 'https://api.github.com/users/obezsmertnyi/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/obezsmertnyi/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/obezsmertnyi/subscriptions',
    organizations_url: 'https://api.github.com/users/obezsmertnyi/orgs',
    repos_url: 'https://api.github.com/users/obezsmertnyi/repos',
    events_url: 'https://api.github.com/users/obezsmertnyi/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/obezsmertnyi/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
  {
    login: 'ibezsmertnyi',
    id: 82649535,
    node_id: 'MDQ6VXNlcjgyNjQ5NTM1',
    avatar_url: 'https://avatars.githubusercontent.com/u/82649535?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ibezsmertnyi',
    html_url: 'https://github.com/ibezsmertnyi',
    followers_url: 'https://api.github.com/users/ibezsmertnyi/followers',
    following_url:
      'https://api.github.com/users/ibezsmertnyi/following{/other_user}',
    gists_url: 'https://api.github.com/users/ibezsmertnyi/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/ibezsmertnyi/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/ibezsmertnyi/subscriptions',
    organizations_url: 'https://api.github.com/users/ibezsmertnyi/orgs',
    repos_url: 'https://api.github.com/users/ibezsmertnyi/repos',
    events_url: 'https://api.github.com/users/ibezsmertnyi/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/ibezsmertnyi/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
  {
    login: 'rslnbzsmrtni10',
    id: 85965904,
    node_id: 'MDQ6VXNlcjg1OTY1OTA0',
    avatar_url: 'https://avatars.githubusercontent.com/u/85965904?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/rslnbzsmrtni10',
    html_url: 'https://github.com/rslnbzsmrtni10',
    followers_url: 'https://api.github.com/users/rslnbzsmrtni10/followers',
    following_url:
      'https://api.github.com/users/rslnbzsmrtni10/following{/other_user}',
    gists_url: 'https://api.github.com/users/rslnbzsmrtni10/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/rslnbzsmrtni10/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/rslnbzsmrtni10/subscriptions',
    organizations_url: 'https://api.github.com/users/rslnbzsmrtni10/orgs',
    repos_url: 'https://api.github.com/users/rslnbzsmrtni10/repos',
    events_url: 'https://api.github.com/users/rslnbzsmrtni10/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/rslnbzsmrtni10/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vadym Bezsmertnyi',
    company: 'CyberLeaf',
    blog: 'https://www.linkedin.com/in/vadim-bezsmertnyy-7666431a2/',
    location: 'Cherkasy',
    email: null,
    hireable: null,
    bio: 'ReactJS/TS Developer',
    twitter_username: null,
    public_repos: 12,
    public_gists: 0,
    followers: 1,
    following: 5,
    created_at: '2020-10-19T18:45:47Z',
    updated_at: '2022-10-21T14:34:42Z',
  },
];

export const DEFAULT_SELECT_USER: TUser = {
  login: 'VadymBezsmertnyi',
  id: 73135527,
  node_id: 'MDQ6VXNlcjczMTM1NTI3',
  avatar_url: 'https://avatars.githubusercontent.com/u/73135527?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/VadymBezsmertnyi',
  html_url: 'https://github.com/VadymBezsmertnyi',
  followers_url: 'https://api.github.com/users/VadymBezsmertnyi/followers',
  following_url:
    'https://api.github.com/users/VadymBezsmertnyi/following{/other_user}',
  gists_url: 'https://api.github.com/users/VadymBezsmertnyi/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/VadymBezsmertnyi/starred{/owner}{/repo}',
  subscriptions_url:
    'https://api.github.com/users/VadymBezsmertnyi/subscriptions',
  organizations_url: 'https://api.github.com/users/VadymBezsmertnyi/orgs',
  repos_url: 'https://api.github.com/users/VadymBezsmertnyi/repos',
  events_url: 'https://api.github.com/users/VadymBezsmertnyi/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/VadymBezsmertnyi/received_events',
  type: 'User',
  site_admin: false,
  name: 'Vadym Bezsmertnyi',
  company: null,
  blog: '',
  location: 'Cherkasy',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 12,
  public_gists: 0,
  followers: 1,
  following: 5,
  created_at: '2020-10-19T18:45:47Z',
  updated_at: '2022-10-05T11:04:37Z',
};
